# https://golangci-lint.run/usage/configuration/
linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - unnamedResult
  gocyclo:
    min-complexity: 15
  golint:
    # The package comment is false positive so the min-confidance needs to be set to at least 0.3
    # Ref https://github.com/golangci/golangci-lint/issues/1556#issuecomment-744021989
    min-confidence: 0.3
  govet:
    check-shadowing: true
  lll:
    line-length: 160
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - errcheck
    - exhaustive
    - gocritic
    - gocyclo
    - gofmt
    - golint
    - gomnd
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - whitespace

issues:
  exclude-use-default: false

run:
  timeout: 10m
  tests: true
